# Generated by Django 3.1.6 on 2021-02-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210208_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
